build:
    context: .
    dockerfile: ba_website/Dockerfile
    services:
      - docker:19.03.11-dind
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $CI_REGISTRY/istnescha/ba-website/ba_backend:latest .
      - docker push $CI_REGISTRY/istnescha/ba-website/ba_backend:latest