version: '3'
services:
  ba-backend:
    image: neilschark/ba-website:ba-backend
    container_name: ba-backend
    working_dir: /backend
    environment:
    - DBDATABASE=ba-db
    - DBHOST=ba-postgres
    - DBPASSWORD=1234
    - DBPORT=5432
    - DBUSER=ba-user
    - SECRET=SECRETKEY
    command: ./run_docker.sh
    expose:
      - 1337
    depends_on:
      - ba-postgres

  ba-nginx:
    image: neilschark/ba-website:ba-nginx
    container_name: ba-nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 0.0.0.0:1337:1337
    depends_on:
      - ba-backend

  ba-postgres:
    image: postgres:11
    container_name: ba-postgres
    environment:
      - POSTGRES_USER=ba-user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ba-db
    volumes:
      - ba-postgres-volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  ba-postgres-volume:
  static_volume:
